name: Test reduction ratio for BDS, big

on:
  # Trigger the workflow on push or pull request
  # push:
  # Trigger the workflow manually
  #schedule:
  # - cron: '0 12 */7 * *'
  workflow_dispatch:

jobs:
  test:
    name: Test reduction ratio for BDS, big
    runs-on: ${{matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [big]
        with_optim_toolbox: [yes]
        solver: [CBDS]
        competitor: [CBDS]
        feature: [plain, badly_scaled, low, medium, high, randomx0_1e-3, randomx0_1, randomx0_10]
        reduction_ratio_1: [1e-6, 1e-8, 1e-10, 1e-12, 1e-14, 1e-16]
        reduction_ratio_2: [1e-6, 1e-8, 1e-10, 1e-12, 1e-14, 1e-16]
        exclude: 
          - reduction_ratio_1: 1e-6
          - reduction_ratio_1: 1e-8
            reduction_ratio_2: 1e-8
          - reduction_ratio_1: 1e-8
            reduction_ratio_2: 1e-10
          - reduction_ratio_1: 1e-8
            reduction_ratio_2: 1e-12
          - reduction_ratio_1: 1e-8
            reduction_ratio_2: 1e-14
          - reduction_ratio_1: 1e-8
            reduction_ratio_2: 1e-16
          - reduction_ratio_1: 1e-10
            reduction_ratio_2: 1e-10
          - reduction_ratio_1: 1e-10
            reduction_ratio_2: 1e-12
          - reduction_ratio_1: 1e-10
            reduction_ratio_2: 1e-14
          - reduction_ratio_1: 1e-10
            reduction_ratio_2: 1e-16
          - reduction_ratio_1: 1e-12
            reduction_ratio_2: 1e-12
          - reduction_ratio_1: 1e-12
            reduction_ratio_2: 1e-14
          - reduction_ratio_1: 1e-12
            reduction_ratio_2: 1e-16
          - reduction_ratio_1: 1e-14
            reduction_ratio_2: 1e-14
          - reduction_ratio_1: 1e-14
            reduction_ratio_2: 1e-16
          - reduction_ratio_1: 1e-16
            reduction_ratio_2: 1e-16

    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clone MatCUTEst
        uses: actions/checkout@v4
        with:
          repository: matcutest/matcutest_compiled
          path: matcutest

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4.0.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd()

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest'));
            install(); cd(root_dir);

            % Conduct your tests
            path_tests = fullfile(root_dir, 'tests');
            cd(path_tests)
            parameters.problem_dim = "${{ matrix.dim }}";
            parameters.parallel = true;
            parameters.feature = "${{ matrix.feature }}";
            parameters.fmin_type = "randomized";
            parameters.solvers_name = ["${{ matrix.solver }}", "${{ matrix.competitor }}"];
            parameters.solvers_options{2}.reduction_factor = [0, ${{ matrix.reduction_ratio_1 }}, ${{ matrix.reduction_ratio_2 }}];

            plot_profile(parameters);

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test_big_reduction_ratio
          path: ./tests/testdata
